# Generated by Django 5.1.6 on 2025-05-01 21:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_category_subscribers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name_category',
            field=models.CharField(help_text='category name', max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(help_text='author of publication', on_delete=django.db.models.deletion.CASCADE, to='news.author'),
        ),
        migrations.AlterField(
            model_name='post',
            name='publication',
            field=models.CharField(choices=[('NW', 'News'), ('AR', 'Article')], default='NW', help_text='type of publication: news or article', max_length=2),
        ),
    ]
