# Generated by Django 5.1.6 on 2025-05-02 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_category_name_category_en_category_name_category_ru_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='subscribers_en',
        ),
        migrations.RemoveField(
            model_name='category',
            name='subscribers_ru',
        ),
        migrations.RemoveField(
            model_name='post',
            name='author_en',
        ),
        migrations.RemoveField(
            model_name='post',
            name='author_ru',
        ),
        migrations.RemoveField(
            model_name='post',
            name='date_creation_en',
        ),
        migrations.RemoveField(
            model_name='post',
            name='date_creation_ru',
        ),
        migrations.RemoveField(
            model_name='post',
            name='publication_en',
        ),
        migrations.RemoveField(
            model_name='post',
            name='publication_ru',
        ),
        migrations.RemoveField(
            model_name='post',
            name='rating_en',
        ),
        migrations.RemoveField(
            model_name='post',
            name='rating_ru',
        ),
    ]
