# Generated by Django 5.1.6 on 2025-05-02 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_remove_category_subscribers_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postcategory_ru',
            name='category_through',
        ),
        migrations.RemoveField(
            model_name='postcategory_ru',
            name='post_through',
        ),
        migrations.RemoveField(
            model_name='post',
            name='post_category_en',
        ),
        migrations.RemoveField(
            model_name='post',
            name='post_category_ru',
        ),
        migrations.DeleteModel(
            name='PostCategory_en',
        ),
        migrations.DeleteModel(
            name='PostCategory_ru',
        ),
    ]
