# Generated by Django 5.1.6 on 2025-05-02 00:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_remove_postcategory_ru_category_through_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name': 'Author', 'verbose_name_plural': 'Authors'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Cqtegories'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'Comment', 'verbose_name_plural': 'Comments'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Publication', 'verbose_name_plural': 'Publications'},
        ),
        migrations.AlterModelOptions(
            name='postcategory',
            options={'verbose_name': 'Relationship between publication and category'},
        ),
        migrations.AlterField(
            model_name='category',
            name='name_category',
            field=models.CharField(help_text='name category', max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_category_en',
            field=models.CharField(help_text='name category', max_length=64, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_category_ru',
            field=models.CharField(help_text='name category', max_length=64, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(help_text='Author of publication', on_delete=django.db.models.deletion.CASCADE, to='news.author'),
        ),
    ]
