# Generated by Django 5.1.6 on 2025-05-02 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_alter_author_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='postcategory',
            options={'verbose_name': 'Post Category'},
        ),
    ]
