# Generated by Django 5.1.6 on 2025-05-02 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_alter_category_options_alter_postcategory_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postcategory',
            options={'verbose_name': 'Post Category', 'verbose_name_plural': 'Post Categories'},
        ),
    ]
