# Generated by Django 5.1.6 on 2025-05-02 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0013_alter_post_options_alter_post_date_creation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name_category',
            field=models.CharField(help_text='name category', max_length=64, unique=True, verbose_name='Category Name'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_category_en',
            field=models.CharField(help_text='name category', max_length=64, null=True, unique=True, verbose_name='Category Name'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_category_ru',
            field=models.CharField(help_text='name category', max_length=64, null=True, unique=True, verbose_name='Category Name'),
        ),
    ]
